backend:
  name: github
  branch: master
  repo: jescowuester/jsco.dev

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "blog title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "blog post", name: "body", widget: "markdown" }
